### ISSUE TITLE
Cereal not building in Ubuntu 22.04

### ISSUE THREAD

**Issue by RaghavPrabhakar66** [flowdriveai/flowpilot#42]
**Describe the bug**
```bash
In file included from /usr/include/capnp/common.h:29:
/usr/include/kj/string.h:24:10: fatal error: 'initializer_list' file not found
#include <initializer_list>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [gen/cpp/car.capnp.os] Error 1
scons: building terminated because of errors.

```
```
➜  flowpilot git:(master) ✗ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
**To Reproduce**
Run `scons` in root directory. 

**Expected behavior**
Scons build succesfull.

**Platform Details**
Desktop:
  - Ubuntu 22.04
  - using GPU

**Additional context**
flowpilot currently works on ubuntu20.04, we should upgrade the requirements to make it compatible with more devices.

**Comment by MankaranSingh** [comment]
What branch is this ?

**Comment by RaghavPrabhakar66** [comment]
Master, premium both. I have faced this issue since April. I have tried changing gcc version. I have even tried adding `initializer_list` header files manually but still no luck.

**Comment by 0312birdzhang** [comment]
What you need is `sudo apt install libstdc++-12-dev`

**Comment by RaghavPrabhakar66** [comment]
To run flowpilot on ubuntu 22.04+, `#include <iterator>` should be added to `opendbc/can/dbc.cc`. We should probably update `opendbc` to latest commit.
Closing this issue for now.
